<MainScreen>
    MDBottomNavigation:

        # Add a NavigationItem for each Navigation.
        MDBottomNavigationItem:
            name: "home"
            text: "Home"
            icon: "alarm-check"
            Button:
                text: "text"
        
        MDBottomNavigationItem:
            name: "setting"
            text: "Настройки"
            icon: "cog-outline"

            # Add Contents here

